// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// const SUPABASE_URL = "https://loqpepftcimqjkiinuwv.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY =
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvcXBlcGZ0Y2ltcWpraWludXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3OTMxNjEsImV4cCI6MjA1NDM2OTE2MX0.R8z0PZx01OoNUEx-CA3yWmFHiI1gSXKKTNpA7D1_zYo";

const SUPABASE_URL = "https://awoszgiaficixepwayqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3b3N6Z2lhZmljaXhlcHdheXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNjA3MDgsImV4cCI6MjA1NDgzNjcwOH0.ctmM5a98HZ_GmdC4aNtAjVFynHe1TccEaNsFhZ6aNaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
