// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loqpepftcimqjkiinuwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvcXBlcGZ0Y2ltcWpraWludXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3OTMxNjEsImV4cCI6MjA1NDM2OTE2MX0.R8z0PZx01OoNUEx-CA3yWmFHiI1gSXKKTNpA7D1_zYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);